### ISSUE TITLE
radiocore.conf galduta

### ISSUE THREAD

**Issue by xabispacebiker** [aritzz/radiocore#1]
Kaixo, ezkerrik asko radiocloud kodea partekatzeagatik.

Radio Cloud eta daemon-a instalatu dut jada Debian 9 Stretch zerbitzari batean (libcurl  manualki instalatu behar nuen), eta orain radiocore instalatzen araso bat dut. Radiocore ondo konpilatzen da baina ez dut radiocore.conf aurkitzen.

Milezker zure denboragatik

**Comment by aritzz** [comment]
Kaixo Xabi!

bin/ direktorioan dago konfigurazio-fitxategia. Bertara konpilatzen da kodea (make erabiliz) eta bertan exekutatzen da konfigurazio-fitxategia adieraziz:
./radiocore radiocore.conf

Ondo izan.
Aritz
