### ISSUE TITLE
[RadioCore] Schedule file could not be read

### ISSUE THREAD

**Issue by xabispacebiker** [aritzz/radiocore#2]
Radiocore instalatuta, baina exekutatzerakoan hau botatzen du:

```
[RadioCore] DB Initialized
[RadioCore] Schedule file could not be read
```

**Comment by aritzz** [comment]
Kaixo Xabi!

Datubasea instalatzeko daukazu. Instala ezazu Radiocloud web bidezko interfazea (instalatzaile bat dauka) eta automatikoki datubase bat instalatuko dizu MySQL zerbitzari batean. Ondoren, datu berberak jar itzazu Radiocore-ren konfigurazio-fitxategian eta martxan jarriko zaizu.

Ondo izan.
Aritz

**Comment by xabispacebiker** [comment]
Hori lehena egin dut, izan ere, databasua instalatuta zegoen. Orain berreinstalatu dut baina errorea botatzen jarraitzen du

**Comment by aritzz** [comment]
Sartu duzu parrilan zerbait erreproduzitzeko? Hutsik badago, ezin du ezer kargatu eta beraz, errorea ematen du.

**Comment by xabispacebiker** [comment]
gauza da ezin dudala ezer programatu egutegian. Bideotxo bat egin dut:
https://youtu.be/CyXxPm0urZs

**Comment by aritzz** [comment]
Kontua da, lehendabizi blokeetan edo kanpoko irratsaioen atalean gehitu behar dituzula nahi dituzun blokeak (musika, programak, etab). Behin gehituta, parrilara sartu eta ezkerreko aldean (orain hutsik duzuna) agertuko dira. Hartu eta parrilara arrastratu behar dituzu eta nahi duzun orduan jarri.

https://youtu.be/Y1Gb7KrnQNY
